version: '3'
services:
  strapi:
    container_name: tribunal-strapi-dev
    build: 
      context: ./strapi
      dockerfile: Dockerfile.dev
    ports:
      - "1338:1338"
    restart: unless-stopped
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/package-lock.json:/opt/package-lock.json
      - ./strapi/.tmp:/opt/app/.tmp
      - ./strapi/.env:/opt/app/.env
    networks:
      - strapi-network
  frontend:
    container_name: tribunal-nextjs-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - strapi-network

volumes:
    strapi-data:

networks:
  strapi-network:
    name: Strapi
    driver: bridge