version: '3'
services:
  strapi:
    container_name: tribunal-strapi-dev
    build: 
      context: ./strapi
      dockerfile: Dockerfile.dev
    ports:
      - "1338:1338"
    restart: unless-stopped
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/package-lock.json:/opt/package-lock.json
      - ./strapi/.tmp:/opt/app/.tmp
      - ./strapi/.env:/opt/app/.env
    networks:
      strapi_network:
        aliases:
          - strapi

  frontend:
    container_name: tribunal-nextjs-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      #args:
      #  - STRAPI_HOST=tribunal-strapi-dev
    environment:
      - NODE_ENV=development
      - STRAPI_HOST=strapi
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      strapi_network:
        aliases:
          - frontend
    depends_on:
      - strapi

volumes:
    strapi-data:

networks:
  strapi_network:
    name: StrapiNet
    driver: bridge
    ipam:
      driver: default