FROM node:16
# Installing libvips-dev for sharp Compatability
RUN apt-get update && apt-get install libvips-dev -y

ARG JWT_SECRET
ARG ADMIN_JWT_SECRET
ARG APP_KEYS
ARG NODE_ENV
ARG HOST
ARG PORT

ENV JWT_SECRET=${JWT_SECRET}
ENV ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
ENV APP_KEYS=${APP_KEYS}
ENV NODE_ENV=${NODE_ENV}
ENV HOST=${HOST}
ENV PORT=${PORT}

WORKDIR /opt/
COPY ./package.json ./package-lock.json ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN npm install
WORKDIR /opt/app
COPY ./ .
RUN npm run build
EXPOSE 1338
CMD ["npm", "run", "develop"]
